### ISSUE TITLE
Movie Details Module

### ISSUE THREAD

**Issue by utchi-kanna** [fssa-batch3/sec_a_utchikanna.neelakandan__corejava_project_2#18]
## Tasks

- [ ] #16
- [ ] #17
- [ ] #19
- [ ] #20

### Attributes:

 - [ ] movieDetailsId (assuming this is equivalent to movie_id)
 - [ ] movieId (assuming this relates to movie_title)
 - [ ] story (assuming this is related to movie_story)
 - [ ] releaseDate (assuming this is related to movie_release_date)
 - [ ] awardName (assuming this is related to movie_award_name)
 - [ ] awardWiki (assuming this is related to movie_award_wiki_url)
 - [ ] movieLink (assuming this is related to movie_image_url)

### Validation

- [ ] validateStory()
- [ ] validateReleaseDate()
- [ ] validateAwardName()
- [ ] validateAwardWiki()
- [ ] validateMovieLink()

### Validation Tests

- [ ] TestValidateStory()
- [ ] TestValidateReleaseDate()
- [ ] TestValidateAwardName()
- [ ] TestValidateAwardWiki()
- [ ] TestValidateMovieLink()
